# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GemeinnuetzigkeitConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finanzamt', models.CharField(blank=True, max_length=300, null=True, verbose_name='Finanzamt')),
                ('vat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT-ID')),
                ('reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='reason for reduced taxes')),
                ('notification_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='last date of notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
