# Generated by Django 2.1.1 on 2018-10-13 11:39

from django.db import migrations

def rename_category(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for doc in Document.objects.filter(category='zuwendungsbestaetigung').all():
        doc.category = 'byro_gemeinnuetzigkeit.receipt'
        doc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('byro_gemeinnuetzigkeit', '0003_gemeinnuetzigkeitconfiguration_receipt_template'),
    ]

    operations = [
        migrations.RunPython(rename_category, migrations.RunPython.noop),
    ]
